### PR TITLE
Adding upsert/insert ignore support

### PR DESCRIPTION
**Pull request by aheuermann**
I know I am missing some docs, will push those up tomorrow. Let me know if the syntax looks good. 

For Postgres, this supports the most common use-case. [There are more extensive options for **conflict_target**](https://www.postgresql.org/docs/9.5/static/sql-insert.html#SQL-ON-CONFLICT) that this does not support. Mysql does not support the concept of `conflict_target` it assumes any/all unique constraints. Postgres, however, requires a target when doing an update.

<br /><br />
I didn't end up doing this in this PR, but I think we could support `Upsert(i1, i2)` but might require some more ORM-ish features depending on how we do it. 
 - Would need an argument for the `conflict_target` for postgres. If inserting structs, we could have a tag that indicates primary key and auto-fill it, but not sure how to indicate this for maps. Would probably need an argument.
- Probably would need a tag or another argument to override certain columns in the case of update timestamps and to ignore things like created if updating. 

Could be that these are options we just add to `ConflictExpression`.

The SQL for this would look like:<br />

**Postgres**
```sql
INSERT INTO table (col1, col2) 
VALUES ('a', 'b'),  ('c', 'd') 
ON CONFLICT (unique_column) UPDATE SET col1= excluded.col1, col2=excluded.col2;
```
*Mysql*
```sql
INSERT INTO table (col1, col2) 
VALUES ('a', 'b'),  ('c', 'd') 
On DUPLICATE KEY UPDATE col1=VALUES(col1), col2=VALUES(col2);
```

### CODE REVIEW

**Comment by aheuermann** [comment]
Here are the sequelize docs on upsert. They call it [`insert_conflict`](http://sequel.jeremyevans.net/rdoc-adapters/classes/Sequel/Postgres/DatasetMethods.html#method-i-insert_conflict)

**Comment by doug-martin** [comment]
I think I agree I like the insert conflict better also

**Comment by aheuermann** [comment]
Updated. This should be g2g.

**Comment by doug-martin** [comment]
👍

**Comment by doug-martin** [comment]
One think I noticed can you update the history.md once you add your changes from this and the other PR noting all the changes in the release?

**Pull request merged**
