### PR TITLE
Do not interpolate literals when prepared=true.

### PR DESCRIPTION
**Pull request by marshallmcmullen**
This addresses https://github.com/doug-martin/goqu/issues/132

It is a reset of closed PR: https://github.com/doug-martin/goqu/pull/151

The gist of this fix is to modify the builders to not interpolate
nil and boolean values so that prepared statements can work properly.
This makes prepared=true work more consistently across all types.

The scope of this change:

(1) Modify literalNil to use a placeholder if prepared=true similar to
literalBool and literalInt

(2) Modify checkBoolExpType to not turn (in)equality on nil or bool
values to an IS expression.

(3) LOTS of tests and examples updated to reflect the new behavior.

(4) Fix bugs from https://github.com/doug-martin/goqu/pull/151 found by
@doug-martin to preserve correct behavior with Is/IsNot and not
incorrectly map them to Eq/NotEq.

### CODE REVIEW

**Comment by marshallmcmullen** [comment]
@doug-martin I couldn't get the closed PR (https://github.com/doug-martin/goqu/pull/151) to reopen. Not sure if there is a permission issue there but there was not a reopen button like I'm accustomed to seeing. So I opened a new PR.

I think this addresses the issues you found in the prior PR. Specifically it preserves the correct behavior with `Is` and `IsNot` instead of incorrectly routing them to `Eq` and `NotEqual`. Please take a look and let me know what you think.

**Comment by marshallmcmullen** [comment]
@doug-martin I found another scenario while testing integrating these changes into our product. The code was also interpolating `DEFAULT` with `prepared=true` which seems incorrect to me. See the changes in https://github.com/doug-martin/goqu/pull/155/commits/b380ab00a3dbaf4eb34777294d73d1530f840b95 and let me know what you think.

**Comment by marshallmcmullen** [comment]
@doug-martin, I made one more change to this PR after integrating this with our product. Basically, do not interpret a literal `DEFAULT` if `prepared=true`. I originally put this in, then backed it out as I couldn't figure out how to make it work for an insert. But I ended up needing this fix for an Update regardless. So I put it back in.

But, I still would like to figure out how to use `goqu.Default()` in an Insert with `prepared=true` as I wasted hours on it and am totally stumped. Let me know if you have ideas.

**Comment by marshallmcmullen** [comment]
> @doug-martin, I made one more change to this PR after integrating this with our product. Basically, do not interpret a literal `DEFAULT` if `prepared=true`. I originally put this in, then backed it out as I couldn't figure out how to make it work for an insert. But I ended up needing this fix for an Update regardless. So I put it back in.
> 
> But, I still would like to figure out how to use `goqu.Default()` in an Insert with `prepared=true` as I wasted hours on it and am totally stumped. Let me know if you have ideas.

To add a little more color to this, suppose I do:

```
// Suppose 'field' is an 'int32' inside database with a default value of 42. I don't expect my code to
// know the default and would instead like to just pick up the default value from the database
ids = goqu.Insert("foo").Prepared(true).Rows(map[string]interface{}{
     "field": goqu.Default(),
})
```

This turns into this code:

```
INSERT INTO "foo" ("field") VALUES ($1)
```

Which looks right to me. But args has:

```
"DEFAULT"
```

At first I thought this was quoted just for logging purposes and didn't think anything about it. However, when I try to execute this using `database/sql`, I see:

```
pq: invalid input syntax for type int32: \"DEFAULT\"
```

**Comment by marshallmcmullen** [comment]
> > @doug-martin, I made one more change to this PR after integrating this with our product. Basically, do not interpret a literal `DEFAULT` if `prepared=true`. I originally put this in, then backed it out as I couldn't figure out how to make it work for an insert. But I ended up needing this fix for an Update regardless. So I put it back in.
> > But, I still would like to figure out how to use `goqu.Default()` in an Insert with `prepared=true` as I wasted hours on it and am totally stumped. Let me know if you have ideas.
> 
> To add a little more color to this, suppose I do:
> 
> ```
> // Suppose 'field' is an 'int32' inside database with a default value of 42. I don't expect my code to
> // know the default and would instead like to just pick up the default value from the database
> ids = goqu.Insert("foo").Prepared(true).Rows(map[string]interface{}{
>      "field": goqu.Default(),
> })
> ```
> 
> This turns into this code:
> 
> ```
> INSERT INTO "foo" ("field") VALUES ($1)
> ```
> 
> Which looks right to me. But args has:
> 
> ```
> "DEFAULT"
> ```
> D At first I thought this was quoted just for logging purposes and didn't think anything about it. However, when I try to execute this using `database/sql`, I see:
> 
> ```
> pq: invalid input syntax for integer: \"DEFAULT\"
> ```

Maybe it's just not the right thing to try to make `DEFAULT` work with prepared=true. I'm inclined at this point to just revert that part of this PR so we can get the rest of these changes moving forward. What are your thoughts @doug-martin ?

**Comment by marshallmcmullen** [comment]
> @doug-martin, I made one more change to this PR after integrating this with our product. Basically, do not interpret a literal `DEFAULT` if `prepared=true`. I originally put this in, then backed it out as I couldn't figure out how to make it work for an insert. But I ended up needing this fix for an Update regardless. So I put it back in.
> 
> But, I still would like to figure out how to use `goqu.Default()` in an Insert with `prepared=true` as I wasted hours on it and am totally stumped. Let me know if you have ideas.

I think this isn't working as it should. I've refactored our company code to not require this anymore. So I'm removing this part of the PR in the interest of getting everything else merged.

I'll approach this other issue afterwards.

**Comment by doug-martin** [comment]
@marshallmcmullen thank you for making those changes. Re-reviewing, with the new set of changes, has made more apparent the other part of the problem which is `goqu.Ex`. The original intention of `Ex` was to make writing `WHERE`'s simple by not have to choose the operator in simple cases and avoiding the more low level identifier DSL, but re-reviewing the PR I now see that this is starting to break down.

Rather than changing more code to address another slew of issues. I think we can simplify this by continuing to use `IS` for (NULL|TRUE|FALSE) fragment, but DO NOT interpolate the nil or boolean values.

So the following query... 

```go
ds := db.From("foo").Where(goqu.Ex{"a": nil})
```
would generate
```sql
SELECT * FROM "foo" WHERE "a" IS NULL
-- PREPARED
SELECT * FROM "foo" WHERE "a" IS ?
```

The downside is a different prepared queries would be created for non nil value. For example
```go
ds := db.From("foo").Where(goqu.Ex{"a": 1})
```
would generate
```sql
SELECT * FROM "foo" WHERE "a" = 1
-- OR
SELECT * FROM "foo" WHERE "a" = ?
```
The same prepared query could be cached for nil or boolean values and the second one for other values. I think this option is better than pushing boilerplate (nil, boolean checks) up to the end user.

Im going to try that out and see if there are other side effects, and report back.

Thanks again for your patience! I know we'll get this right as I know it is important to you and your team, I just want to make sure goqu does not create headaches for a developer that doesn't know how the internals work.

**Comment by doug-martin** [comment]
@marshallmcmullen take a look at https://github.com/doug-martin/goqu/compare/null_literals_simple?expand=1 and let me know what you think.

**Comment by marshallmcmullen** [comment]
> @marshallmcmullen take a look at https://github.com/doug-martin/goqu/compare/null_literals_simple?expand=1 and let me know what you think.

@doug-martin I like this direction. I think it's a lot simpler than what I was trying to do. I think this looks great.

**Comment by marshallmcmullen** [comment]
@doug-martin these changes look great to me. I'm happy with your proposed changes.

**Comment by doug-martin** [comment]
@marshallmcmullen cool, Ill close this PR and reopen with the new set of changes.

**Comment by surenzeroonelabs** [comment]
Is there a way to enable `prepared` statements for all `postgres` queries?
Something like `goqu.New("postgres", db).Prepared(true))`.

**Pull request closed without merging**
